recipes = {
    'breakfast': [
        {'id': 1,
         'title': 'Buttermilk Fluffy Pancakes',
         'category': 'Breakfast',
         'servings': '12',
         'vegan': 'No',
         'ingredients': ['3 cups plain flour', '3 tbsp white sugar', '3 tsp baking powder', '1 1/2 tsp baking soda', '3/4 tsp salt', '3 cups buttermilk', '1/2 cup milk', '3 eggs', '1/3 cup melted butter'],
         'instructions': ['Combine all the dry ingredients in a bowl.', 'In a separate bowl, mix together the buttermilk, milk, eggs, and melted butter.', "Add the wet mixture into the dry mixture. Don't over-mix the batter or you will end up with a tough pancake",
                          'Get your pan or griddle hot and greased with butter', 'Pour or scoop your batter into the pre-heated pan and wait until bubbles appear on your pancake, and then flip it with your spatula.', 'Continue with the rest of your batter.',
                          'Decorate with toppings of your choice and enjoy!.']
        },
        {'id': 2,
         'title': 'French Toast',
         'category': 'Breakfast',
         'servings': '8',
         'vegan': 'No',
         'ingredients': ['4 large eggs', '2/3 cup milk', '1/4 cup all-purpose flour', '1/4 cup granulated sugar', '1/4 teaspoon salt', '1 teaspoon ground cinnamon', '1 teaspoon vanilla extract', '8 thick slices bread', 'Selection of fruits of your liking'],
         'instructions': ['Preheat griddle to 350 degrees F or heat a skillet over medium heat.', 'Add all ingredients, except the bread, to a blender or if using a shallow dish and whisking by hand, mix flour and eggs first then add remaining batter ingredients.',
                          'Dip bread slices into the batter, dredging them well on both sides, and place on hot, greased griddle or skillet.', 'Cook for a few minutes, until the bottom of the breads starts to get golden brown. Flip and cook on the other side the same.',
                          'Move to a plate. Serve warm with any spred or syrup, and fruits of your liking.']
        },
        {'id': 3,
         'title': 'Vegan Banana Pancakes',
         'category': 'Breakfast',
         'servings': '12',
         'vegan': 'Yes',
         'ingredients': ['1 large ripe banana (around 150g)', '2 tbsp golden caster sugar', '¼ tsp fine salt', '2 tbsp vegetable oil, plus extra for cooking', '120g self-raising flour', '½ tsp baking powder', '150ml oat, almond milk or soya milk',
                         'syrup, sliced banana and berries, to serve (optional)'],
         'instructions': ['Mash the banana in a mixing bowl. Stir in the sugar, salt, and oil. Add the flour and baking powder and mix thoroughly. Make a well in the center and gradually whisk in the milk. The batter should be a thick, droppable consistency.',
                          'Heat a little oil in a frying pan over medium heat. Add 2 tbsp of the batter to make American-style pancakes. Fry on each side for 2-3 mins until golden. Serve with syrup, sliced banana, and berries, if you like.']
        },
        {'id': 4,
         'title': 'Avocado Toast',
         'category': 'Breakfast',
         'servings': '1',
         'vegan': 'Yes',
         'ingredients': ['1 ripe avocado', '½ lemon', 'big pinch chili flakes', '2 slices sourdough bread', 'good drizzle extra virgin olive oil'],
         'instructions': ['Cut the avocado in half and carefully remove its stone, then scoop out the flesh into a bowl.', 'Squeeze in the lemon juice then mash with a fork to your desired texture.', 'Season to taste with sea salt, black pepper, and chili flakes.', 'Toast your bread, drizzle over the oil then put the avocado on top.']
        },
        {'id': 5,
         'title': 'Full Irish Breakfast',
         'category': 'Breakfast',
         'servings': '1',
         'vegan': 'No',
         'ingredients': ['1 cooked potato, sliced thinly', '130g baked beans', 'a little olive oil', '1 Irish pork sausage', '3 mushrooms', 'knob of butter', '2 slices of black pudding cut to desired thickness', '3 cherry tomatoes', '2 rashers eye bacon', '2 eggs', '2 slices of Irish brown bread, or bacon, chive and cheese soda bread'],
         'instructions': ['Preheat the oven to 180 C.', 'On a baking sheet, pop the hashbrowns or leftover potatoes with a little oil into the oven. Bake until golden and season with salt and pepper.', 'In a small saucepan, heat the baked beans. While they are cooking, start on the fried bits.',
                          'In a large skillet, cook the sausages on medium heat. Once they are ready to turn, add the mushrooms to your pan with a knob of butter. Let the butter melt and stir through the mushrooms.', 'Add the black pudding to the pan and cook for 4 minutes on each side.', 'Into the pan add the tomatoes and bacon. Cook for a couple of minutes.',
                          'When everything else is fully cooked and ready to serve, crack the eggs into the pan and cook until sunny side up.', 'Pop all the cooked ingredients on a plate and serve with 2 slices of soda bread (and butter), a cup of tea, and a glass of orange juice.']
        },
        {'id': 6,
         'title': 'Poached Egg on Avocado & Feta Toast',
         'category': 'Breakfast',
         'servings': '2',
         'vegan': 'No',
         'ingredients': ['2 tbsp white wine vinegar', '2 large eggs', '1 avocado', '50g feta', '1 tsp chilli flakes', 'Juice of  ½ a lemon', '2 slices of sourdough'],
         'instructions': ["Fill a large saucepan with water, add the vinegar and bring to a hard boil over a high heat. Once boiling, reduce the heat so the water is simmering, then use a spoon to swirl the water into a whirlpool. Crack in both eggs and cook for 2 1/2 mins.", 
                          "In a small bowl, mash the avocado, feta, chilli flakes and lemon juice, and season well with black pepper. Toast the bread.", "Pile the avocado and feta on the toast, then put a poached egg on top of each."]
        },
        {'id': 7,
         'title': 'Omelette',
         'category': 'Breakfast',
         'servings': '1',
         'vegan': 'No',
         'ingredients': ['2 knobs of butter', 'large handful spinach', '2 free-range eggs', '15g/½oz cheddar, grated', 'salt and freshly ground black pepper'],
         'instructions': ["Melt a knob of butter in a frying pan placed over a medium heat. Add the spinach and cook for 1–2 minutes, until wilted. Season with salt and pepper. Tip out onto a plate and set aside.", 
                          "In a bowl, beat the eggs until just mixed. Return the frying pan to a medium–high heat, add the remaining butter and melt until beginning to foam, then swirl it around the pan.", "Pour in the beaten eggs, then tilt the pan to distribute the eggs evenly. Leave for 20 seconds, until the eggs begin to bubble.", 
                          "Working quickly, use a spatula or wooden spoon to draw in the sides of the eggs to the centre, incorporating the butter. Gently shake the pan to redistribute the egg to the edges.", "Sprinkle over the cheese and spinach while the egg is still slightly runny in the middle, then remove the pan from the heat. The residual heat will continue to cook the egg. Season with salt and pepper.", 
                          "Using a spatula, fold one third of the omelette into the middle, then turn the omelette onto a warm plate folding over itself. Serve immediately."]
        },
        {'id': 8,
         'title': 'Overnight Oats',
         'category': 'Breakfast',
         'servings': '1',
         'vegan': 'No',
         'ingredients': ['¼ tsp ground cinnamon', '50g rolled porridge oats', '2 tbsp natural yogurt', '50g mixed berries', 'drizzle of honey', '½ tbsp nut butter'],
         'instructions': [" The night before serving, stir the cinnamon and 100 ml water (or milk) into your oats with a pinch of salt.", "The next day, loosen with a little more water (or milk) if needed. Top with the yogurt, berries, a drizzle of honey and the nut butter."]
        },
        {'id': 9,
         'title': 'Granola bowl',
         'category': 'Breakfast',
         'servings': '1',
         'vegan': 'Yes',
         'ingredients': [' 1/2 cup of yogurt of your choice', '1/4 cup of fruits of your choice', '1/2 Tbsp of seeds, nuts, fruits shavings (i.e. coconut shavings) of your choice', '1/4 cup granola'],
         'instructions': ["Place the yogurt in a bowl.", "Add the washed fruit. ", "Top with the seeds, nuts, coconut, and granola.", "Serve and enjoy!"]
        },
        {'id': 10,
         'title': 'Grilled Cheese',
         'category': 'Breakfast',
         'servings': '4 Sandwiches',
         'vegan': 'No',
         'ingredients': ['8 slices of thick sliced sandwich bread', '4 Tbsp unsalted butter', '4 slices medium cheddar cheese', '4 slices Gouda cheese', '4 slices Havarti cheese'],
         'instructions': ["Spread 1/2 Tbsp of butter on one side of each slice of bread.", "Set a skillet over medium/low heat and place 2 slices of bread in the skillet with the butter side down.", "Stack cheeses on one piece of toast: cheddar, havarti, then gouda. Once the breads are golden brown, close the sandwich with the crisp sides on the outside.", "Continue cooking until the bread is a rich golden brown, flip once and press down lightly to help the bread stick to the cheese. Total cooking time should be one 5-6 minutes. Keep the heat on medium low for the breads to toast slowly, giving your cheese a chance to fully melt and adhere to the bread.", "Once you see the cheese has melted and breads are browned, remove to a plate and cut in half diagonally to serve. Repeat with the next sandwich"]
        },
    ],
    'mains': [
        {'id': 7,
         'title': 'Beef and Broccoli',
         'category': 'Mains',
         'servings': '4 people',
         'vegan': 'No',
         'ingredients': ['1 lb / 455g flank steak, thinly sliced', '2 tbsp olive oil, divided', '1 lb / 455g broccoli', '2 tsp sesame seed, optional for garnish', 'Sauce ingredients', '1 tsp fresh grated ginger',
                         '2 tsp grated garlic', '1/2 cup / 120ml hot water', '6 tbsp low sodium soy sauce', '3 tbsp light brown sugar', '1 1/2 tbsp corn starch', '1/4 tsp black pepper', '2 tbsp sesame oil'],
         'instructions': ['Optional but this dish is best paired with white rice, so start cooking your rice first before making this!', 'Freeze your steak for half an hour for easy slicing',
                          'Combine all your sauce ingredients until everything is dissolved and well combined', 'Over medium heat, add 1 tbsp of your olive oil and saute your broccoli florets for 4 - 5 mins until broccoli is bright green and crisp-tender. Transfer to a plate.',
                          'Increase heat to high and add 1 tbsp of olive oil to the pan. Add beef and saute 2 minutes per side or just until cooked through.', 'Add sauce mixture and reduce heat to medium/low. Allow it to simmer for 3 - 4 minutes. Add broccoli and stir to combine. If sauce is too thick, carefully add 1 tbsp at a time until your desired thickness is achieved.',
                          'Serve with rice and enjoy!']
        },
        {'id': 8,
            'title': 'Roast Chicken and Salad',
            'category': 'Mains',
            'servings': '6 people',
            'vegan': 'No',
            'ingredients': ['1 bunch of oregano (20g)', '1 bulb of garlic extra virgin olive oil', '1 lemon', '3 small onions', '1 x 1.5kg whole chicken', '2 knobs of unsalted butter', 'olive oil', '4 rashers of higher-welfare smoked streaky bacon', '2 thick slices of sourdough bread', "4 large handfuls of mixed lettuce, such as oakleaf, little gem, lamb's lettuce, or rocket", 
                            '50g radishes', '50g Roquefort cheese', '1 handful of shelled unsalted walnuts,' '20g Parmesan cheese', '2 heaped teaspoons Dijon mustard', '2 tablespoons red wine vinegar', '1 teaspoon runny honey'],
            'instructions': ['Preheat the oven to 200ºC/400ºF/gas 6. Pick the oregano leaves into a pestle and mortar, add a good pinch of sea salt and black pepper, and pound into a paste. Peel and pound in 2 cloves of garlic, then muddle in 2 tablespoons of extra virgin olive oil and a squeeze of lemon juice.', 
                            'Halve the onions, leaving the skin on, cut the remaining garlic into 3 big chunks, and place it all cut-side down in a roasting tray.', 'Use a sharp knife to cut through the chicken along the backbone, allowing you to open it out like a book. Press it flat with your hands, then pull up the skin at the tip of the breasts and use your finger or a spatula to gently separate the skin from the breast meat.', 
                            'Poke a knob of butter and some of the herby marinade into each pocket, then rub the rest of the marinade over the top of the chicken and sit it in the tray. Roast for 50 minutes to 1 hour, or until cooked through.', 'Put a large non-stick frying pan on a medium-high heat and, once hot, add 1 tablespoon of olive oil. Slice and add the bacon with a good pinch of black pepper, and cook until golden, tossing regularly, then remove, leaving the tasty fat behind.', 
                            'Chop the bread into rough cubes and sprinkle into the pan, tossing regularly until golden and crisp, then turn the heat off.', 'For the dressing, whisk the mustard and vinegar with 3 tablespoons each of olive oil and extra virgin olive oil until smooth, add the honey, then season to perfection.', 
                            'Click apart your lettuce leaves, wash and spin dry, then arrange over a large serving platter. Finely slice and add the radishes, crumble over the Roquefort and walnuts, and finely grate over the Parmesan. Add the lardons and croutons, then drizzle over the dressing, to taste (save the rest in a clean jam jar in the fridge for another day). Finish with a few finely chopped chives or a scattering of fennel tops, if using.', 
                            'Carve up the chicken, plate up with the salad as you wish, and enjoy.']
        },
        {'id': 9,
            'title': 'Chilli Con Carne',
            'category': 'Mains',
            'servings': '4 people',
            'vegan': 'No',
            'ingredients': ['1 large onion', '1 red pepper', '2 garlic cloves', '1 tbsp oil', '1 heaped tsp hot chilli powder (or 1 level tbsp if you only have mild)', '1 tsp paprika', '1 tsp ground cumin', '500g lean minced beef', '1 beef stock cube', '400g can chopped tomatoes', '½ tsp dried marjoram', '1 tsp sugar', '2 tbsp tomato purée', '410g can red kidney beans', 'Plain boiled long grain rice, to serve', 
                            'Sour cream, to serve'],
            'instructions': ['Prepare your vegetables. Chop 1 large onion into small dice, about 5mm square. The easiest way to do this is to cut the onion in half from root to tip, peel it and slice each half into thick matchsticks lengthways, not quite cutting all the way to the root end so they are still held together. Slice across the matchsticks into neat dice.', 
                             'Cut 1 red pepper in half lengthways, remove stalk and wash the seeds away, then chop. Peel and finely chop 2 garlic cloves.', 'Start cooking. Put your pan on the hob over a medium heat. Add 1 tbsp oil and leave it for 1-2 minutes until hot (a little longer for an electric hob).', 
                             'Add the onion and cook, stirring fairly frequently, for about 5 minutes, or until the onion is soft, squidgy and slightly translucent.', 'Tip in the garlic, red pepper, 1 heaped tsp hot chilli powder or 1 level tbsp mild chilli powder, 1 tsp paprika and 1 tsp ground cumin.', 'Give it a good stir, then leave it to cook for another 5 minutes, stirring occasionally.', 
                             'Brown 500g lean minced beef. Turn the heat up a bit, add the meat to the pan and break it up with your spoon or spatula. The mix should sizzle a bit when you add the mince.', 'Keep stirring and prodding for at least 5 minutes, until all the mince is in uniform, mince-sized lumps and there are no more pink bits. Make sure you keep the heat hot enough for the meat to fry and become brown, rather than just stew.', 
                             'Make the sauce. Crumble 1 beef stock cube into 300ml hot water. Pour this into the pan with the mince mixture.', 'Add a 400g can of chopped tomatoes. Tip in ½ tsp dried marjoram, 1 tsp sugar and add a good shake of salt and pepper. Squirt in about 2 tbsp tomato purée and stir the sauce well.', 
                             'Simmer it gently. Bring the whole thing to the boil, give it a good stir and put a lid on the pan. Turn down the heat until it is gently bubbling and leave it for 20 minutes.', "Check on the pan occasionally to stir it and make sure the sauce doesn't catch on the bottom of the pan or isn't drying out. If it is, add a couple of tablespoons of water and make sure that the heat really is low enough. After simmering gently, the saucy mince mixture should look thick, moist and juicy.", 
                             'Drain and rinse a 410g can of red kidney beans in a sieve and stir them into the chilli pot. Bring to the boil again, and gently bubble without the lid for another 10 minutes, adding a little more water if it looks too dry.', 'Taste a bit of the chilli and season. It will probably take a lot more seasoning than you think.', 'Now replace the lid, turn off the heat and leave your chilli to stand for 10 minutes before serving. This is really important as it allows the flavours to mingle.', 
                             'Serve with soured cream and plain boiled long grain rice.']
        },
        {'id': 10,
            'title': 'Kimchi Stew',
            'category': 'Mains',
            'servings': '4 people',
            'vegan': 'No',
            'ingredients': ['1 pound kimchi, cut into bite size pieces', '¼ cup kimchi brine', '½ pound pork shoulder (or pork belly)', '½ package of tofu (optional), sliced into ½ inch thick bite size pieces', '3 green onions', '1 medium onion, sliced (1 cup)', '1 teaspoon kosher salt', '2 teaspoons sugar', '2 teaspoons gochugaru (Korean hot pepper flakes)', '1 tablespoon gochujang (hot pepper paste)', '1 teaspoon toasted sesame oil', 
                            '2 cups of anchovy stock (or chicken or beef broth)'],
            'instructions': ['Put the anchovies, daikon, green onion roots, and dried kelp in a sauce pan.', 'Add the water and boil for 20 minutes over medium high heat.', 'Lower the heat to low for another 5 minutes, and strain', 'Place the kimchi and kimchi brine in a shallow pot. Add pork and onion.', 'Slice 2 green onions diagonally and add them to the pot.', 'Add salt, sugar, hot pepper flakes, and hot pepper paste. Drizzle sesame oil over top and add the anchovy stock.', 'Cover and cook for 10 minutes over medium high heat.',
                             'Open and mix in the seasonings with a spoon. Lay the tofu over top.', 'Cover and cook another 10 to 15 minutes over medium heat. Chop 1 green onion and put it on the top of the stew. Remove from the heat and serve right away with rice.']
        },
        {'id': 11,
            'title': 'Vegan Carbonara',
            'category': 'Mains',
            'servings': '4',
            'vegan': 'Yes',
            'ingredients': ['360g wholewheat spaghetti', '85g unsalted cashew nuts', '2 tsp bouillon powder', '2 tsp English mustard powder', '1 tsp olive oil', '200g baby chestnut mushrooms, halved and thinly sliced', '3 garlic cloves, 2 finely grated', '1 tsp smoked paprika', '2 courgettes (about 320g), peeled and grated', '4 tsp nutritional yeast flakes, optional'],
            'instructions': ['Boil the spaghetti for 10 mins or following pack instructions until al dente, reserving a little of the water. Put the cashews, bouillon and mustard in a bowl, then pour over 350ml boiling water.', 'Heat the oil in a large non-stick pan. Add the mushrooms and grated garlic, and stir-fry over a high heat until the mushrooms are cooked and starting to crisp up. Take off the heat, stir in the paprika, then tip onto a plate and set aside.', 
                             'Add the grated courgette to the pan and cook, stirring every now and then until softened. Meanwhile, whizz the soaked cashews, whole garlic clove and nutritional yeast flakes, if using, with a hand blender until completely smooth. Tip the mixture into the pan with the courgettes and briefly stir over the heat.', 'Add the spaghetti and toss in the cashew and courgette mixture until well coated, then toss through the smoky mushrooms.']
        },
        {'id': 12,
            'title': 'Air Fry Baked Potato',
            'category': 'Mains',
            'servings': '4',
            'vegan': 'Yes',
            'ingredients': ['4 baking potatoes (about 250g each)', '½ tbsp sunflower oil', 'toppings of your choice, such as butter, cheese, baked beans or tuna mayonnaise'],
            'instructions': ["Scrub the potatoes, then pat dry with kitchen paper. Transfer to a plate, drizzle over the oil and rub it into the skins using your hands so the potatoes are well-coated. Season with salt and pepper – the salt will help the skins crisp up.", 
                             "Arrange the potatoes in a single layer in an air fryer basket. Set the air fryer to 200C and cook for 40-50 mins, or until a sharp knife goes through the potatoes easily. Check the potatoes after 20 mins – if they seem to be browning too quickly on one side, turn them over using tongs, then check again after another 20 mins to ensure they're cooked through.", 
                             "The size of the potato and model of air fryer may affect the cooking time. To speed up the cooking time, you can microwave on high for 8-10 mins before airfrying (check after 15-20 mins). When ready, the skin should be crisp and the inside tender and fluffy. Split and serve immediately with the toppings of your choice."]
        },
        {'id': 13,
            'title': 'Vegetable stew',
            'category': 'Mains',
            'servings': '4',
            'vegan': 'Yes',
            'ingredients': [' 1 tbsp olive oil, or rapeseed oil', '1 onion, finely chopped', '3 garlic cloves, sliced', '1 tsp smoked paprika', '½ tsp ground cumin', '1 tbsp dried thyme', '3 medium carrots (about 200g), sliced', '2 medium celery sticks (about 120g), finely sliced', '1 red pepper, chopped', '1 yellow pepper, chopped', 
                            '2 x 400g cans tomatoes, or peeled cherry tomatoes', '1 vegetable stock cube, made up to 250ml', '2 courgettes (about 300g), sliced thickly', '2 sprigs fresh thyme', '250g cooked puy lentils'],
            'instructions': ["Heat the olive or rapeseed oil in a large, lidded, heavy-based pan over a medium heat. Lower the heat slightly then add the onion, cooking gently and stirring occasionally, for 5-10 mins until softened.", "Stir in the garlic cloves, smoked paprika, ground cumin, dried thyme, carrots, celery sticks, red and yellow peppers, and cook for 5 mins.", 
                             "Tip in the tomatoes along with the vegetable stock, courgettes and thyme sprigs. Give it a good stir, cover, and cook for 20-25 mins.", "Remove the thyme sprigs and discard. Stir in the cooked lentils and bring back to a simmer for 5 mins until warmed through. Serve with wild and white basmati rice, mash or quinoa."]
        },
        {'id': 14,
            'title': 'Chicken Cordon Bleu',
            'category': 'Mains',
            'servings': '8',
            'vegan': 'No',
            'ingredients': ['8 thin slices ham', '226.8 g Swiss cheese sliced or shredded', '4 boneless skinless chicken breasts , about 2 pounds', 'salt and freshly ground black pepper', '84 g corn flakes cereal , crushed (or substitute breadcrumbs)', '85 g butter , melted'],
            'instructinos': [" Pat the chicken dry with paper towels. Use a sharp knife to cut each chicken breast in half horizontally to create two chicken breast halves.", "Place the chicken breast halves between two sheets of plastic wrap and use a meat mallet or rolling pin to pound them into thin and evenly (be careful not to pound so hard that the meat tears.).", 
                             "Top each piece of chicken with a slice of ham and a ham handful of shredded cheese. Roll tightly, tucking the sides a little, and place on a new piece of plastic wrap.", "Wrap the chicken tightly in the plastic wrap, pinching the excess plastic on the sides to create a tootsie-roll shape and twisting them to create a firm chicken roll. Refrigerate the wrapped chicken bundles for at least 30-minutes or up to one day in advance.", 
                             "Preheat the oven to 400 degrees F. Remove chicken from the fridge, unwrap and season with salt and pepper. Add cornflakes to a food processor and pulse into fine crumbs. Add crumbs to a shallow dish or pie plate. Melt butter in a separate shallow dish.", "Dip the chicken bundles in melted butter, and then into the cornflake crumbs, pressing lightly to help the crumbs stick to the chicken. Transfer to a lightly greased baking sheet.", 
                             "Bake on the centre oven rack for about 30 minutes, or until chicken is cooked through (160 degrees on a thermometer inserted into the chicken, not the filling.)"]
        },
        {'id': 15,
            'title': 'Fried spring roll',
            'category': 'Mains',
            'servings': '15 - 20',
            'vegan': 'No',
            'ingredients': ['1 tbsp oil', '2 garlic cloves , finely chopped or minced', '400 g / 13 oz pork mince (ground pork), or chicken or turkey', '6 dried shiitake mushrooms soaked in boiling water OR 8 fresh', '1 1/2 cups shredded carrot (1 large or 2 small)', '1 1/2 cups (heaped) bean sprouts', '1 1/2 cups (packed) shredded green cabbage (any type is fine)', '1 tsp cornflour / cornstarch', '1 1/2 tbsp Oyster Sauce', 
                            '2 tsp soy sauce', '15 – 20 spring roll wrappers, defrosted (21.5 cm / 8” squares) OR 35 – 40 small spring roll wrappers, or Egg Roll wrappers to make Egg Rolls', '2 tsp cornflour (for sealing rolls)', '1 tbsp water (for sealing rolls)', 'Oil for frying'],
            'instructions': ["Heat oil in a skillet or wok over high heat. Add garlic, stir quickly, then add pork. Cook, breaking it up as you go, until it turns white.", "Add carrot, bean sprouts, cabbage and mushrooms. Cook for 3 minutes or until vegetables are wilted. Add cornflour, soy sauce and Oyster sauce, cook for 1 minute until the liquid is gone. The Filling should not be watery, it should be kind of sticky.", 
                             "Chill the filling", "Mix cornflour and water in a small bowl (for sealing the rolls).", "Carefully peel off one spring roll wrapper, keep the others covered under a damp tea towel.", "Place the wrapper with the smooth side down in a diamond position. Place a very heaped dessert spoon of filling on the bottom. Roll up halfway, fold sides in, then finish rolling. Use cornflour sludge to seal. They should be about 12 cm / 5″ long, 2.5cm / 1″ wide once wrapped.", 
                             "Pour enough oil in a wok or large saucepan (Note 4) so it is double the height of the spring rolls. Heat on medium high until hot – stick a bamboo chopstick or wooden spoon handle in, if rapid bubbles appear, then it's hot enough.", "Carefully place spring rolls in the oil (about 4 – 5 at a time) and cook, turning occasionally, until deep golden – around 1 1/2 – 2 minutes. Transfer to paper towels to drain."]
        },
        {'id': 16,
            'title': 'Veggie Noodles',
            'category': 'Mains',
            'servings': '4',
            'vegan': 'Yes',
            'ingredients': ['2 tablespoons vegetable oil(30 mL)', '5 cloves garlic, minced', '4 green onions, sliced, divided', '2 carrots, cut into matchsticks', '1 cup snap peas(100 g)', '2 tablespoons brown sugar', '3 tablespoons soy sauce', '9 oz dried rice noodles(250 g), cooked'],
            'instructions': ["Heat the vegetable oil in a large skillet over medium heat. Add the garlic and 3 green onions and cook for 2–3 minutes, until fragrant and tender. Add the carrots and snap peas, then stir in the brown sugar and soy sauce.", "Add the noodles and toss for a couple of minutes, until the noodles are well-coated and the vegetables are tender. Season with salt and pepper.", "Serve immediately, garnished with the remaining green onion."]
        }
    ],
    'dessert': [
        {'id': 17,
         'title': 'Red Velvet Cake',
         'category': 'Dessert',
         'servings': '6',
         'vegan': 'No',
         'ingredients': ['2 1/2 cups / 300g plain flour', '1 tsp salt', '1 tsp baking soda', '1/2 cup / 113g unsalted room temp. butter', '1 1/2 cups / 300g granulated sugar', '2 large room temp. eggs', '2 tsp vanilla extract', '2 tbsp cocoa powder', '1 cup / 240ml room temp. buttermilk', '1 tbsp white vinegar', '1 - 2 tbsp liquid red food colouring',
                         'Cream Cheese Frosting', '454g room temp. cream cheese', '1 1/2 cups / 340g room temp. unsalted butter', '1 tsp vanilla extract', 'A pinch of salt', '675g confectioners sugar'],
         'instructions': ['Preheat oven to 177 degrees C. Butter and flour, or alternatively line your cake pans with baking paper.', 'In a medium bowl, sift flour salt, and baking powder', 'In another bowl, cream the butter using an electric whisk, a stand mixer, or by hand, on medium speed. Add in the sugar and mix on medium until light and fluffy.',
                          'Add the eggs one at a time and then add the vanilla.', 'Sift the cocoa powder into the butter mixture and beat just until combined.', 'For the wet ingredients, mix the buttermilk, vinegar, and red food colouring.', 'Carefully add the dry ingredients into the butter mixture, followed by half of the buttermilk mixture. Repeat with the remaining dry mixture and buttermilk mixture.',
                          'Divide the batter among the prepared pans.', 'Bake for about 25 - 30 mins and cool.', 'Prepare frosting while cakes are cooling by creaming the butter, cream cheese, and vanilla extract together. Add sugar slowly while on low speed until it is fluffy.', 'Layer cooled cakes with frosting and enjoy!']
        },
        {'id': 18,
         'title': 'Chocolate Cheesecake',
         'category': 'Dessert',
         'servings': '10',
         'vegan': 'No',
         'ingredients': ['24 chocolate biscuits', '5 tbsp unsalted butter g, melted', '1/4 cup coffee hot', '1 cup bittersweet chocolate', '3/4 cup semisweet chocolate', '24 oz cream cheese 608g, room temperature', '1 pinch salt', '1 cup sugar 200g', '1/4 cup sour cream', '1 tbsp vanilla extract 15ml', '4 eggs large, room temperature', '3 tbsp All purpose flour', '1/3 cup semisweet chocolate', '1/3 cup cream', '2 cups heavy cream', 
                         '1/4 cup powdered sugar', '2 tsp vanilla extract', '3 tbsp cocoa powder plus more if needed'],
        'instructions': ["Preheat oven to 177C.", "Crush your chocolate biscuits and pour in melted butter. Mix together until it forms into a  wet sand-like consistency.", "Transfer mixture to your springform pan and spread out with a spatula so the crumbs are evenly distributed on the bottom and toward the side as well. Press into a flat layer using a tall glass.", "Bake for about 10 minutes at 177C, or until fragrant and a darker golden colour.", 
                         " Remove from oven, set aside. Reduce oven temperature to 163C.", "Place chocolate chips in a bowl then pour the hot coffee over them. Mix a bit then microwave in a few 20 second intervals as needed, stirring in between. Once almost all of the chocolate is melted, cover and set aside, the residual heat should melt the remaining chocolate while you make the batter. I used a combination of semi sweet and bittersweet but you can use the chocolate you like best for this recipe.", 
                         "Add room temperature cream cheese to a stand mixer fitted with a paddle attachment and mix at medium speed to cream.", "Add the sugar and the salt to the bowl and mix on medium until creamy. Scrape the bowl down and mix until completely homogenous.", "Add sour cream and vanilla extract, mix well then add the eggs and yolks one at a time, allowing each to incorporate before adding the next. Sprinkle in the flour and continue to mix. Scrape the bowl down and mix until completely smooth.", 
                         "Pour in the melted chocolate and mix on low until combined. Scrape the bowl down and mix once more.", "Pour the batter into the prepared 8 or 9 inch springform pan. The batter will not rise much at all during this low and slow bake so you can fill it up almost to the top.", "Place springform pan into a large roasting pan or on a baking sheet (this makes sure there are no leaks and it's easier to remove from the oven.", 
                         "Bake at 163C for 20 minutes then reduce temperature to 300F and bake another 30 minutes or until cake's edge is set but centre is still wobbly. Turn the oven off but leave the door closed and allow the cake to rest for an additional hour in the oven. Remove from the oven and cool to room temperature then cover with a towel or paper towel and chill overnight. You can enjoy the cheesecake after a few hours of chilling but it's much easier to cut if you've chilled it overnight.", 
                         "Melt the chocolate and cream in a small bowl. You can use a double boiler, microwave or heat the cream before mixing in.", "Spread the ganache onto the cake and return to the refrigerator to chill while you make the chocolate whipped cream.", "Add the cold cream, vanilla extract, and powdered sugar to the bowl of your stand mixer. Sift in the cocoa powder then mix with a whisk attachment until semi-stiff peaks form.", "Transfer whipped cream to a piping bag fitted with a star attachment and pipe onto the cake's edge using small circular motions."]
        },
        {'id': 19,
         'title': 'Marshmallow Rice krispie',
         'category': 'Dessert',
         'servings': '24',
         'vegan': 'No',
         'ingredients': ['¼ cup butter', '4 cups miniature marshmallows', '5 cups crispy rice cereal'],
         'instructions': ['Melt butter in a large saucepan over low heat.', 'Add marshmallows and stir until melted and well combined. Cook 2 minutes longer, stirring constantly. Remove from heat.', 'Stir in crispy rice cereal until well coated.', 'Press mixture evenly and firmly into a buttered 9x13-inch pan using a buttered spatula or waxed paper.', 'Cut into 2-inch squares when cool.']
        },
        {'id': 20,
         'title': 'Tiramisu',
         'category': 'Dessert',
         'servings': '9',
         'vegan': 'No',
         'ingredients': ['357 g heavy whipping cream', '226.8 g container mascarpone cheese ,room temperature', '66.67 g granulated sugar', '4 g vanilla extract', '354.88 g cold espresso', '45 g coffee flavoured liqueur ,optional (Kahlua or DaVinci brands)', '1 package Lady Fingers ,Savoiardi brand can be found in the cookie aisle at your local grocery store, or online', 'Cocoa powder for dusting the top'],
         'instructions': ["Add whipping cream to a mixing bowl and beat on medium speed with electric mixers (or use a stand mixer). Slowly add sugar and vanilla and continue to beat until stiff peaks. Add mascarpone cheese and fold in until combined. Set aside.", "Add coffee and liqueur to a shallow bowl. Dip the lady fingers in the coffee (Don't soak them, just quickly dip them on both sides to get them wet) and lay them in a single layer on the bottom of an 8x8'' or similar size pan. ", 
                          "Smooth half of the mascarpone mixture over the top. Add another layer of dipped lady fingers. Smooth remaining mascarpone cream over the top.", "Dust cocoa powder generously over the top (I use a fine mesh strainer to do this). Refrigerate for at least 3-4 hours or up to overnight before serving."]
        },
        {'id': 21,
         'title': 'Chocolate Hazelnut Mousse',
         'category': 'Dessert',
         'servings': '8 small remekins',
         'vegan': 'No',
         'ingredients': ['200g/7oz chocolate hazelnut spread', '50ml/2fl oz full-fat milk', '600ml/20fl oz double cream', '1 tbsp cornflour', '3 tbsp icing sugar', '100g/3½oz roasted chopped hazelnuts', 'whipped cream, from a can, to serve (optional)', 'cocoa powder, for dusting (optional)'],
         'instructions': ['Pop the chocolate hazelnut spread into a bowl with the milk and heat in the microwave in 10-second bursts until the mixture is runny and viscous, but not steaming hot. This should not take more than 20 seconds. Set aside to cool.', 'Put the cream into a large bowl with the cornflour and icing sugar and begin whipping. As soon as the mixture begins to thicken, pour in the chocolate hazelnut spread and keep whipping until stiff peaks are formed when the whisk is removed from the bowl.', 
                          'Fold through the hazelnuts (keeping a tablespoon back for decorating), then spoon into a serving dish or individual ramekins. If you want it to look extra special, you can pipe the mousse in.', 'Serve with whipped cream if desired, with an extra sprinkling of hazelnuts on top and an optional dusting of cocoa powder.']
        },
        {'id': 22,
         'title': 'Banana Bread',
         'category': 'Dessert',
         'servings': '8 - 10',
         'vegan': 'Yes',
         'ingredients': ['3 large black bananas', '75ml vegetable oil or sunflower oil, plus extra for the tin', '100g brown sugar', '225g plain flour (or use self-raising flour and reduce the baking powder to 2 heaped tsp)', '3 heaped tsp baking powder', '3 tsp cinnamon or mixed spice', '50g dried fruit or nuts (optional)'],
         'instructions': ['Heat oven to 200C/180C fan/gas 6. Mash 3 large black peeled bananas with a fork, then mix well with 75g vegetable or sunflower oil and 100g brown sugar.', 'Add 225g plain flour, 3 heaped tsp baking powder and 3 tsp cinnamon or mixed spice, and combine well. Add 50g dried fruit or nuts, if using.', 'Bake in an oiled, lined 2lb loaf tin for 20 minutes. Check and cover with foil if the cake is browning.', 'Bake for another 20 minutes, or until a skewer comes out clean.']
        },
        {'id': 23,
         'title': 'Chocolate Molten Caked',
         'category': 'Dessert',
         'servings': '6',
         'vegan': 'No',
         'ingredients': ['100g butter, plus extra to grease', '100g dark chocolate, chopped', '150g light brown soft sugar', '3 large eggs', '½ tsp vanilla extract', '50g plain flour', 'single cream, to serve'],
         'instructions': ["Heat oven to 200C/180C fan/gas 6. Butter 6 dariole moulds or basins well and place on a baking tray.", "Put 100g butter and 100g chopped dark chocolate in a heatproof bowl and set over a pan of hot water (or alternatively put in the microwave and melt in 30 second bursts on a low setting) and stir until smooth. Set aside to cool slightly for 15 mins.", 
                          "Using an electric hand whisk, mix in 150g light brown soft sugar, then 3 large eggs, one at a time, followed by ½ tsp vanilla extract and finally 50g plain flour. Divide the mixture among the darioles or basins.", "You can now either put the mixture in the fridge, or freezer until you're ready to bake them. Can be cooked straight from frozen for 16 mins, or bake now for 10-12 mins until the tops are firm to the touch but the middles still feel squidgy.", 
                          "Carefully run a knife around the edge of each pudding, then turn out onto serving plates and serve with single cream."]
        },
        {'id': 24,
         'title': "S'mores Dip",
         'category': 'Dessert',
         'servings': '1 tray',
         'vegan': 'No',
         'ingredients': [' 200g milk chocolate', '2 tbsp full-fat milk', '350g mini marshmallows', '100g digestive biscuits', '100g strawberries, washed and hulled', '100g pineapple chunks', 'Skewers'],
         'instruction': ["Heat the chocolate, milk and 200g of the marshmallows in an ovenproof frying pan over a low heat until melted and smooth. Top with the remaining marshmallows in circles so that the whole surface is covered.", "Grill on high for 1-2 mins until the marshmallows are toasted. Serve with digestives and strawberry and pineapple skewers for dunking."]
        },
        {'id': 25,
         'title': 'Vanilla Panna Cotta',
         'category': 'Dessert',
         'servings': '4',
         'vegan': 'No',
         'ingredients': [' 2 ½ sheets gelatine', '150ml milk', '400ml double cream', '60g caster sugar', '1 vanilla pod, split lengthways', 'fresh strawberries, to serve', 'strawberry compote, to serve'],
         'instructions': ["Add the sheets of gelatine to a bowl of cold water and soak for 5 mins.", 
                          "Pour the milk and cream into a saucepan with the sugar and vanilla seeds (to scrape the seeds out of the pod, use the back of a knife). Stir to combine and bring to a simmer, then remove from the heat. Take the gelatine out of the cold water and squeeze out the excess, then add to the milk mixture. Stir until completely dissolved. Tip into four ramekins and place in the fridge to set for at least a couple of hours.", 
                          "To serve, turn each ramekin upside-down onto a serving plate. If the panna cotta won't drop out, carefully dip the ramekin in a bowl of warm water to loosen it. Serve with a drizzle of strawberry compote and sliced fresh strawberries."]
        },
        {'id': 26,
         'title': 'No-bake Chocolate tart',
         'category': 'Dessert',
         'servings': '8',
         'vegan': 'No',
         'ingredients': ['200g pack all-butter biscuit', '100g butter', '1 tbsp golden syrup or honey', '100g bar dark chocolate', '100g bar milk chocolate', '1 tsp vanilla extract', '2 tbsp icing sugar, plus extra for dusting', '200ml whipping cream', '3 tbsp crème fraîche, to decorate', '200g raspberry, to serve'],
         'instructions': ["Crush the biscuits by putting them in a large, strong, plastic food bag and bashing with a rolling pin. Melt the butter with the syrup or honey in the microwave, then stir in the biscuits. Press onto the base and up the sides of a 12 x 36cm rectangular tin (or 23-25cm round flan tin) and chill while you make the filling", 
                          "Break up the two chocolate bars and put in a large bowl. Melt in the microwave for 2-3 mins on Medium, stirring halfway through. Stir in the vanilla extract, then sift in the icing sugar. Whip the cream until it just holds its shape, then fold into the melted chocolate. Pour into the prepared tin and smooth the top. Chill for at least 2 hrs or for up to 2 days.", 
                          "Just before serving, remove the tart from the tin and slide it onto a flat plate (loosen edges first with the tip of a small pointed knife). You will find it easier to remove the tart if you leave it at room temperature for 30 mins. Put a few tsp of crème fraîche along the centre of the tart (or around the edges if the tart is circular) and top each with a raspberry, then dust lightly with icing sugar. Cut into thin slices and serve with extra raspberries on the side."]
        },
        {'id': 27,
         'title': 'Chocolate tart',
         'category': 'Dessert',
         'servings': '12 - 14',
         'vegan': 'Yes',
         'ingredients': ['350g digestive biscuits', '2 tbsp cocoa powder', '1 tbsp plain flour', '1 tbsp golden syrup', '125-175g vegan margarine or butter, plus extra for the tin', '2 x 400g cans coconut milk, chilled', '200g dark chocolate', '1 tbsp golden syrup'],
         'instructions': ["Heat the oven to 200C/180C fan/gas 6. Crush the biscuits to crumbs in a bowl using the end of a rolling pin or by pulsing in a food processor. Mix in the cocoa powder, flour, syrup and enough vegan margarine or butter to create a dough. Butter a 23cm loose bottom tart tin and press the mixture into the tin.", "Bake in the oven for 10-12 mins, then leave to cool in the tin.", 
                          "Meanwhile, make the filling. Open the cans of coconut milk which will have separated with the water at the top and the thick coconut at the bottom. Discard the water (or use it to make a smoothie) and tip the thick coconut into a bowl.", 
                          "Break the dark chocolate into pieces and melt in the microwave on high in 10-second bursts, stirring in between, or in a heatproof bowl set over a pan of simmering water until smooth. Add the coconut along with the golden syrup and whisk together, beating hard until there are no lumps of coconut left.", "Pour the filling over the base of the tart and put in the fridge to set for 3-4 hrs, or overnight."]
        },
        {'id': 28,
         'title': 'Apple Crumble',
         'category': 'Dessert',
         'servings': '4',
         'vegan': 'Yes',
         'ingredients': ['575g / 3 medium apples, peeled, cored and sliced to 1 cm thick', '2 tbsp golden caster sugar', '175g plain flour', '110g golden caster sugar', '110g dairy-free spread (we used Vitalite dairy-free spread)', '1 tbsp rolled oats', '1 tbsp demerara sugar', 'oat-based vegan cream or custard, to serve'],
         'instructions': ["Heat the oven to 190C. Toss the apples with 2 tbsp golden caster sugar and put in a 23cm round baking dish at least 5cm deep, or a 20cm square dish. Flatten down with your hand.", "For the crumble topping, mix the flour and sugar in a bowl with a good pinch of salt. Rub the dairy-free spread in with your fingertips until the mixture looks like moist breadcrumbs. Shake the bowl and any big bits will come to the surface – rub these in too.", 
                          "Pour the crumble mix over the apples to form a pile in the centre, then use a fork to even out. Gently press the surface with the back of the fork so the crumble holds together and goes crisp, then lightly drag the fork over the top for a decorative finish. Sprinkle the oats and demerara sugar over evenly.", "Place on a baking tray and put in the oven for 35-40 mins, until the top is golden and the apples feel very soft when you insert a small, sharp knife. Leave to cool for 10 mins before serving."]
        }
    ]
}

# Helper function to find a recipe by ID
def get_recipe_by_id(recipe_id):
    for category in recipes.values():
        for recipe in category:
            if recipe['id'] == recipe_id:
                return recipe
    return None

